FROM rust:1.76 as builder

WORKDIR /app
RUN cargo install cargo-watch

COPY ./ ./

RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates tzdata libpq-dev gcc libc6-dev curl gnupg lsb-release \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 8000

ENV TZ=Etc/UTC 

