apiVersion: v1
kind: Service
metadata:
    name: gatekeeper-service
    annotations:
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: '443'
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:381492239882:certificate/00235d38-e53d-40d5-8843-e6d1c7f3d042
    labels:
        app: gatekeeper-service
spec:
    type: LoadBalancer
    selector:
        app: assertly
        name: assertly-gatekeeper-service-pod
    ports:
        - name: http
          protocol: TCP
          port: 80
          targetPort: 8000
        - name: https
          protocol: TCP
          port: 443
          targetPort: 8000
