apiVersion: v1
kind: Secret
metadata:
    name: assertly-webdriver-service-secrets
type: Opaque
data:
    AWS_ACCESS_KEY_ID: QUtJQVZSVVZWVFlGT0lXU042N1c=
    AWS_SECRET_ACCESS_KEY: NldwS1Z4U1pmNEp6R2U0ZHpKU01YVm4vViswYkh5WDdCcWF2Yy95bg==
    AWS_REGION: dXMtd2VzdC0y
