# Use the same base image
FROM node:18

# Set working directory
WORKDIR /usr/src/app
VOLUME [ "/usr/src/app" ]

# Install global dependencies
RUN npm install @nestjs/cli -g
RUN npm install prisma -g

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install project dependencies
RUN npm install

# Expose port 3000
EXPOSE 3000

RUN npx prisma generate
# Run the application in development mode
# You might need to adjust this command according to your application's needs
CMD ["npm", "run", "start:dev"]