apiVersion: v1
kind: Service
metadata:
    name: ai-agent-service-service
    labels:
        app: ai-agent-service-service
spec:
    type: ClusterIP
    selector:
        app: assertly
        name: assertly-ai-agent-service-pod
    ports:
        - name: http
          protocol: TCP
          port: 80
          targetPort: 8000
