apiVersion: v1
kind: Service
metadata:
    name: identity-service
    labels:
        app: identity-service
spec:
    type: ClusterIP
    selector:
        app: assertly
        name: assertly-identity-service-pod
    ports:
        - name: http
          protocol: TCP
          port: 80
          targetPort: 8000
